# Generated by Django 3.1.4 on 2021-01-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_classifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cardboard',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='glass',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='metal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='paper',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='plastic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='trash',
            field=models.IntegerField(default=0),
        ),
    ]
